openapi: 3.0.0
info:
  version: 1.0.0
  title: WordPress Custom API
  description: Documentation for the custom REST API in WordPress
paths:
  /react/v1/posts:
    get:
      summary: Retrieve all posts
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
    post:
      summary: Create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
  /react/v1/posts/{id}:
    get:
      summary: Retrieve a specific post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    put:
      summary: Update a specific post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostInput'
      responses:
        '200':
          description: Post updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    delete:
      summary: Delete a specific post
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Post deleted successfully
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          format: int64
        slug:
          type: string
        link:
          type: string
        title:
          type: string
        featured_image:
          type: string
        categories:
          type: array
          items:
            $ref: '#/components/schemas/Category'
        content:
          type: string
        meta_fields:
          type: array
          items:
            $ref: '#/components/schemas/MetaField'
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
    MetaField:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    PostInput:
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        meta_fields:
          type: array
          items:
            $ref: '#/components/schemas/MetaField'
